// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIlyCtI4aM_newqgFJylxwleSz2i34mI',
    appId: '1:231536197711:web:a9c466c18f9c509cd0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    authDomain: 'haywatch-ai.firebaseapp.com',
    storageBucket: 'haywatch-ai.firebasestorage.app',
    measurementId: 'G-JQRGYT1W4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_XHqwdH9Qc3vu_YqIW0ggA7PEcXCDUE',
    appId: '1:231536197711:android:5ce7b454a7500d54d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tcYxKiFjX3mpcD3liDe0I33Ki7fJYJc',
    appId: '1:231536197711:ios:3ae81d770a39d7d4d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.firebasestorage.app',
    iosBundleId: 'com.example.haywatchAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tcYxKiFjX3mpcD3liDe0I33Ki7fJYJc',
    appId: '1:231536197711:ios:3ae81d770a39d7d4d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.firebasestorage.app',
    iosBundleId: 'com.example.haywatchAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIlyCtI4aM_newqgFJylxwleSz2i34mI',
    appId: '1:231536197711:web:95d29a82d9fef859d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    authDomain: 'haywatch-ai.firebaseapp.com',
    storageBucket: 'haywatch-ai.firebasestorage.app',
    measurementId: 'G-KJJTYM0BBF',
  );
}
