// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIlyCtI4aM_newqgFJylxwleSz2i34mI',
    appId: '1:231536197711:web:a9c466c18f9c509cd0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    authDomain: 'haywatch-ai.firebaseapp.com',
    storageBucket: 'haywatch-ai.appspot.com',
    measurementId: 'G-JQRGYT1W4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_XHqwdH9Qc3vu_YqIW0ggA7PEcXCDUE',
    appId: '1:231536197711:android:4195dd4ac2521f66d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tcYxKiFjX3mpcD3liDe0I33Ki7fJYJc',
    appId: '1:231536197711:ios:e1b21252d49bce6fd0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.appspot.com',
    iosBundleId: 'com.ardmoreff.haywatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tcYxKiFjX3mpcD3liDe0I33Ki7fJYJc',
    appId: '1:231536197711:ios:992177a4d15af60fd0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    storageBucket: 'haywatch-ai.appspot.com',
    iosBundleId: 'com.ardmoreff.haywatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIlyCtI4aM_newqgFJylxwleSz2i34mI',
    appId: '1:231536197711:web:95d29a82d9fef859d0ea3a',
    messagingSenderId: '231536197711',
    projectId: 'haywatch-ai',
    authDomain: 'haywatch-ai.firebaseapp.com',
    storageBucket: 'haywatch-ai.appspot.com',
    measurementId: 'G-KJJTYM0BBF',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux.');
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for fuchsia.');
    }
  }
}
